[package]
name = "realtime_css_gtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk={version='0.17.1', package='gtk'}
glib="0.17.10"
sourceview4="0.4.0"
